### ISSUE TITLE
Xcode 12에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by TrueShine** [IGAWorksDev/SDK-IOS-Abx.Remaster-CocoaPod#1]
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler: Pods/AdBrixRemastered/AdBrixRM.framework/Modules/AdBrixRM.swiftmodule/x86_64.swiftmodule

**Comment by junggate** [comment]
저희도 동일한 이슈가 있는데, 언제 처리해주시나요
Xcode12로 올렸는데 Adbrix 때문에 빌드 안되고 있습니다.

**Comment by TrueShine** [comment]
https://help.adbrix.io/hc/ko/articles/360003068234
